name: Test

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        default: '24'
        required: false
    secrets:
      CODECOV_TOKEN:
        required: false

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm
      - run: npm ci
      - run: npm run test:coverage
      - name: Upload coverage
        if: github.ref == 'refs/heads/main' && inputs.node-version == '24'
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          disable_search: true
          verbose: true
          fail_ci_if_error: true
